#!/usr/bin/env node
/*
 * Builds both targets from src/ (no dependencies needed):
 *   obsidian-plugin/main.js + styles.css   -> copy the folder into <vault>/.obsidian/plugins/local-gantt/
 *   standalone/local-gantt.html            -> a single self-contained page, open it in any browser
 */
const fs = require('fs');
const path = require('path');

const root = __dirname;
const read = (p) => fs.readFileSync(path.join(root, p), 'utf8');
const write = (p, s) => { fs.writeFileSync(path.join(root, p), s); console.log('wrote', p); };
const banner = '/* Generated by build.js from src/ — edit the sources, not this file. */\n';

const core = read('src/gantt-core.js');
const css = read('src/gantt.css');

// Escape non-ASCII so the plugin is immune to file-encoding mix-ups.
const ascii = (js) => js.replace(/[^\x00-\x7f]/g, (c) => '\\u' + c.charCodeAt(0).toString(16).padStart(4, '0'));
write('obsidian-plugin/main.js', ascii(`${banner}'use strict';\n${core}\n${read('src/obsidian-plugin.js')}`));
write('obsidian-plugin/styles.css', `${banner}${css}\n${read('src/obsidian.css')}`);

const html = read('src/standalone.html')
  .replace('/*__CSS__*/', () => css)
  .replace('/*__CORE__*/', () => core)
  .replace('/*__APP__*/', () => read('src/standalone-app.js'));
write('standalone/local-gantt.html', html.replace('<!doctype html>', `<!doctype html>\n<!-- Generated by build.js from src/ -->`));
